### ISSUE TITLE
"Learn More" button is not working

### ISSUE THREAD

**Issue by MStefanov** [rndsolutions/hawkcd.io#1]
Steps to reproduce:
1. Open http://www.hawkcd.io/
2. Navigate to the bottom of the page.
3. You will notice "Learn More" button
4. Click it and observe

Actual Result:
Nothing happens

Expected result
It should either lead you to another page or another section from the current page.
The other way is to just remove it

**Comment by rminchev1** [comment]
"Learn More" no longer exists
